using System;

internal static class VehicleCatalog
{
    internal sealed class VehicleCategory
    {
        internal VehicleCategory(string name, VehicleEntry[] vehicles)
        {
            Name = name;
            Vehicles = vehicles;
        }

        internal string Name { get; }
        internal VehicleEntry[] Vehicles { get; }
    }

    internal sealed class VehicleEntry
    {
        internal VehicleEntry(string displayName, string modelName)
        {
            DisplayName = displayName;
            ModelName = modelName;
        }

        internal string DisplayName { get; }
        internal string ModelName { get; }
    }

    internal static readonly VehicleCategory[] Categories =
    {
        new VehicleCategory("Compacts", new VehicleEntry[]
        {
            new VehicleEntry("2015polstang", "2015polstang"),
            new VehicleEntry("Asbo", "asbo"),
            new VehicleEntry("Blista", "blista"),
            new VehicleEntry("Brioso R/A", "brioso"),
            new VehicleEntry("Brioso 300", "brioso2"),
            new VehicleEntry("Brioso 300 Widebody", "brioso3"),
            new VehicleEntry("Club", "club"),
            new VehicleEntry("Dilettante", "dilettante"),
            new VehicleEntry("Dilettante", "dilettante2"),
            new VehicleEntry("Issi", "issi2"),
            new VehicleEntry("Issi Classic", "issi3"),
            new VehicleEntry("Apocalypse Issi", "issi4"),
            new VehicleEntry("Future Shock Issi", "issi5"),
            new VehicleEntry("Nightmare Issi", "issi6"),
            new VehicleEntry("Blista Kanjo", "kanjo"),
            new VehicleEntry("Panto", "panto"),
            new VehicleEntry("Prairie", "prairie"),
            new VehicleEntry("Rhapsody", "rhapsody"),
            new VehicleEntry("Weevil", "weevil"),
        }),
        new VehicleCategory("Sedans", new VehicleEntry[]
        {
            new VehicleEntry("Asea", "asea"),
            new VehicleEntry("Asea", "asea2"),
            new VehicleEntry("Asterope", "asterope"),
            new VehicleEntry("Asterope GZ", "asterope2"),
            new VehicleEntry("Cinquemila", "cinquemila"),
            new VehicleEntry("Chavos V6", "driftchavosv6"),
            new VehicleEntry("Cognoscenti 55", "cog55"),
            new VehicleEntry("Cognoscenti 55 (Armored)", "cog552"),
            new VehicleEntry("Cognoscenti", "cognoscenti"),
            new VehicleEntry("Cognoscenti (Armored)", "cognoscenti2"),
            new VehicleEntry("Deity", "deity"),
            new VehicleEntry("Hardy", "hardy"),
            new VehicleEntry("Hardy", "drifthardy"),
            new VehicleEntry("Emperor", "emperor"),
            new VehicleEntry("Emperor", "emperor2"),
            new VehicleEntry("Emperor", "emperor3"),
            new VehicleEntry("Fugitive", "fugitive"),
            new VehicleEntry("Glendale", "glendale"),
            new VehicleEntry("Glendale Custom", "glendale2"),
            new VehicleEntry("Impaler SZ", "impaler5"),
            new VehicleEntry("Ingot", "ingot"),
            new VehicleEntry("Intruder", "intruder"),
            new VehicleEntry("Minimus", "minimus"),
            new VehicleEntry("Turreted Limo", "limo2"),
            new VehicleEntry("Premier", "premier"),
            new VehicleEntry("Primo", "primo"),
            new VehicleEntry("Primo Custom", "primo2"),
            new VehicleEntry("Regina", "regina"),
            new VehicleEntry("Rhinehart", "rhinehart"),
            new VehicleEntry("Romero Hearse", "romero"),
            new VehicleEntry("Schafter", "schafter2"),
            new VehicleEntry("Schafter V12 (Armored)", "schafter5"),
            new VehicleEntry("Schafter LWB (Armored)", "schafter6"),
            new VehicleEntry("Stafford", "stafford"),
            new VehicleEntry("Stanier", "stanier"),
            new VehicleEntry("Stratum", "stratum"),
            new VehicleEntry("Stretch", "stretch"),
            new VehicleEntry("Super Diamond", "superd"),
            new VehicleEntry("Surge", "surge"),
            new VehicleEntry("Tailgater", "tailgater"),
            new VehicleEntry("Tailgater S", "tailgater2"),
            new VehicleEntry("Warrener", "warrener"),
            new VehicleEntry("Warrener HKR", "warrener2"),
            new VehicleEntry("Washington", "washington"),
        }),
        new VehicleCategory("SUVs", new VehicleEntry[]
        {
            new VehicleEntry("Aleutian", "aleutian"),
            new VehicleEntry("Astron", "astron"),
            new VehicleEntry("Baller", "baller"),
            new VehicleEntry("Baller", "baller2"),
            new VehicleEntry("Baller LE", "baller3"),
            new VehicleEntry("Baller LE LWB", "baller4"),
            new VehicleEntry("Baller LE (Armored)", "baller5"),
            new VehicleEntry("Baller LE LWB (Armored)", "baller6"),
            new VehicleEntry("Baller ST", "baller7"),
            new VehicleEntry("Baller ST-D", "baller8"),
            new VehicleEntry("BeeJay XL", "bjxl"),
            new VehicleEntry("Cavalcade", "cavalcade"),
            new VehicleEntry("Cavalcade", "cavalcade2"),
            new VehicleEntry("Cavalcade XL", "cavalcade3"),
            new VehicleEntry("Contender", "contender"),
            new VehicleEntry("Dorado", "dorado"),
            new VehicleEntry("Dubsta", "dubsta"),
            new VehicleEntry("Dubsta", "dubsta2"),
            new VehicleEntry("Everon RS", "everon3"),
            new VehicleEntry("FQ 2", "fq2"),
            new VehicleEntry("Granger", "granger"),
            new VehicleEntry("Granger 3600LX", "granger2"),
            new VehicleEntry("Gresley", "gresley"),
            new VehicleEntry("Habanero", "habanero"),
            new VehicleEntry("Huntley S", "huntley"),
            new VehicleEntry("Issi Rally", "issi8"),
            new VehicleEntry("I-Wagen", "iwagen"),
            new VehicleEntry("Jubilee", "jubilee"),
            new VehicleEntry("Landstalker", "landstalker"),
            new VehicleEntry("Landstalker XL", "landstalker2"),
            new VehicleEntry("Mesa", "mesa"),
            new VehicleEntry("Mesa", "mesa2"),
            new VehicleEntry("Novak", "novak"),
            new VehicleEntry("Patriot", "patriot"),
            new VehicleEntry("Patriot Stretch", "patriot2"),
            new VehicleEntry("Radius", "radi"),
            new VehicleEntry("Rebla GTS", "rebla"),
            new VehicleEntry("Rocoto", "rocoto"),
            new VehicleEntry("Seminole", "seminole"),
            new VehicleEntry("Seminole Frontier", "seminole2"),
            new VehicleEntry("Serrano", "serrano"),
            new VehicleEntry("Squaddie", "squaddie"),
            new VehicleEntry("Toros", "toros"),
            new VehicleEntry("Vivanite", "vivanite"),
            new VehicleEntry("Woodlander", "woodlander"),
            new VehicleEntry("XLS", "xls"),
            new VehicleEntry("XLS (Armored)", "xls2"),
        }),
        new VehicleCategory("Coupes", new VehicleEntry[]
        {
            new VehicleEntry("Cognoscenti Cabrio", "cogcabrio"),
            new VehicleEntry("FR36", "driftfr36"),
            new VehicleEntry("Exemplar", "exemplar"),
            new VehicleEntry("F620", "f620"),
            new VehicleEntry("Felon", "felon"),
            new VehicleEntry("Felon GT", "felon2"),
            new VehicleEntry("FR36", "fr36"),
            new VehicleEntry("Jackal", "jackal"),
            new VehicleEntry("Kanjo SJ", "kanjosj"),
            new VehicleEntry("Oracle XS", "oracle"),
            new VehicleEntry("Oracle", "oracle2"),
            new VehicleEntry("Postlude", "postlude"),
            new VehicleEntry("Previon", "previon"),
            new VehicleEntry("Sentinel XS", "sentinel"),
            new VehicleEntry("Sentinel", "sentinel2"),
            new VehicleEntry("Windsor", "windsor"),
            new VehicleEntry("Windsor Drop", "windsor2"),
            new VehicleEntry("Zion", "zion"),
            new VehicleEntry("Zion Cabrio", "zion2"),
        }),
        new VehicleCategory("Muscles", new VehicleEntry[]
        {
            new VehicleEntry("Blade", "blade"),
            new VehicleEntry("Brigham", "brigham"),
            new VehicleEntry("Broadway", "broadway"),
            new VehicleEntry("Buccaneer", "buccaneer"),
            new VehicleEntry("Buccaneer Custom", "buccaneer2"),
            new VehicleEntry("Buffalo STX", "buffalo4"),
            new VehicleEntry("Buffalo EVX", "buffalo5"),
            new VehicleEntry("Chino", "chino"),
            new VehicleEntry("Chino Custom", "chino2"),
            new VehicleEntry("Clique", "clique"),
            new VehicleEntry("Clique Wagon", "clique2"),
            new VehicleEntry("Coquette BlackFin", "coquette3"),
            new VehicleEntry("Deviant", "deviant"),
            new VehicleEntry("Dominator", "dominator"),
            new VehicleEntry("Pisswasser Dominator", "dominator2"),
            new VehicleEntry("Dominator GTX", "dominator3"),
            new VehicleEntry("Apocalypse Dominator", "dominator4"),
            new VehicleEntry("Future Shock Dominator", "dominator5"),
            new VehicleEntry("Nightmare Dominator", "dominator6"),
            new VehicleEntry("Dominator ASP", "dominator7"),
            new VehicleEntry("Dominator GTT", "dominator8"),
            new VehicleEntry("Dominator GT", "dominator9"),
            new VehicleEntry("Dominator FX", "driftdominator10"),
            new VehicleEntry("Drift Yosemite", "driftyosemite"),
            new VehicleEntry("Dukes", "dukes"),
            new VehicleEntry("Duke O'Death", "dukes2"),
            new VehicleEntry("Beater Dukes", "dukes3"),
            new VehicleEntry("Ellie", "ellie"),
            new VehicleEntry("Eudora", "eudora"),
            new VehicleEntry("Faction", "faction"),
            new VehicleEntry("Faction Custom 1", "faction2"),
            new VehicleEntry("Faction Custom Donk", "faction3"),
            new VehicleEntry("Gauntlet", "gauntlet"),
            new VehicleEntry("Redwood Gauntlet", "gauntlet2"),
            new VehicleEntry("Gauntlet Classic", "gauntlet3"),
            new VehicleEntry("Gauntlet Hellfire", "gauntlet4"),
            new VehicleEntry("Gauntlet Classic Custom", "gauntlet5"),
            new VehicleEntry("Gauntlet Hellfire", "driftgauntlet4"),
            new VehicleEntry("Greenwood", "greenwood"),
            new VehicleEntry("Hermes", "hermes"),
            new VehicleEntry("Hotknife", "hotknife"),
            new VehicleEntry("Hustler", "hustler"),
            new VehicleEntry("Impaler", "impaler"),
            new VehicleEntry("Apocalypse Impaler", "impaler2"),
            new VehicleEntry("Future Shock Impaler", "impaler3"),
            new VehicleEntry("Nightmare Impaler", "impaler4"),
            new VehicleEntry("Impaler LX", "impaler6"),
            new VehicleEntry("Apocalypse Imperator", "imperator"),
            new VehicleEntry("Future Shock Imperator", "imperator2"),
            new VehicleEntry("Nightmare Imperator", "imperator3"),
            new VehicleEntry("Lurcher", "lurcher"),
            new VehicleEntry("Manana Custom", "manana2"),
            new VehicleEntry("Moonbeam", "moonbeam"),
            new VehicleEntry("Moonbeam Custom", "moonbeam2"),
            new VehicleEntry("Nightshade", "nightshade"),
            new VehicleEntry("Peyote Gasser", "peyote2"),
            new VehicleEntry("Phoenix", "phoenix"),
            new VehicleEntry("Picador", "picador"),
            new VehicleEntry("Rat-Loader", "ratloader"),
            new VehicleEntry("Rat-Truck", "ratloader2"),
            new VehicleEntry("Ruiner", "ruiner"),
            new VehicleEntry("Ruiner 2000", "ruiner2"),
            new VehicleEntry("Ruiner", "ruiner3"),
            new VehicleEntry("Ruiner ZZ-8", "ruiner4"),
            new VehicleEntry("Sabre Turbo", "sabregt"),
            new VehicleEntry("Sabre Turbo Custom", "sabregt2"),
            new VehicleEntry("Slamvan", "slamvan"),
            new VehicleEntry("Lost Slamvan", "slamvan2"),
            new VehicleEntry("Slamvan Custom", "slamvan3"),
            new VehicleEntry("Apocalypse Slamvan", "slamvan4"),
            new VehicleEntry("Future Shock Slamvan", "slamvan5"),
            new VehicleEntry("Nightmare Slamvan", "slamvan6"),
            new VehicleEntry("Stallion", "stalion"),
            new VehicleEntry("Burger Shot Stallion", "stalion2"),
            new VehicleEntry("Tahoma Coupe", "tahoma"),
            new VehicleEntry("Tampa", "tampa"),
            new VehicleEntry("Weaponized Tampa", "tampa3"),
            new VehicleEntry("Tampa GT", "tampa4"),
            new VehicleEntry("Tulip", "tulip"),
            new VehicleEntry("Tulip M-100", "tulip2"),
            new VehicleEntry("Vamos", "vamos"),
            new VehicleEntry("Vigero", "vigero"),
            new VehicleEntry("Vigero ZX", "vigero2"),
            new VehicleEntry("Vigero ZX Convertible", "vigero3"),
            new VehicleEntry("Virgo", "virgo"),
            new VehicleEntry("Virgo Classic Custom", "virgo2"),
            new VehicleEntry("Virgo Classic", "virgo3"),
            new VehicleEntry("Voodoo Custom", "voodoo"),
            new VehicleEntry("Voodoo", "voodoo2"),
            new VehicleEntry("Weevil Custom", "weevil2"),
            new VehicleEntry("Yosemite", "yosemite"),
            new VehicleEntry("Drift Yosemite", "yosemite2"),
        }),
        new VehicleCategory("Sports Classic", new VehicleEntry[]
        {
            new VehicleEntry("Ardent", "ardent"),
            new VehicleEntry("Roosevelt", "btype"),
            new VehicleEntry("Franken Stange", "btype2"),
            new VehicleEntry("Roosevelt Valor", "btype3"),
            new VehicleEntry("Casco", "casco"),
            new VehicleEntry("Cheburek", "cheburek"),
            new VehicleEntry("Cheetah Classic", "cheetah2"),
            new VehicleEntry("LSCM Cheetah Classic", "cheetah3"),
            new VehicleEntry("Coquette Classic", "coquette2"),
            new VehicleEntry("Deluxo", "deluxo"),
            new VehicleEntry("Dynasty", "dynasty"),
            new VehicleEntry("Fagaloa", "fagaloa"),
            new VehicleEntry("Feltzer Classic", "feltzer3"),
            new VehicleEntry("GT500", "gt500"),
            new VehicleEntry("Infernus Classic", "infernus2"),
            new VehicleEntry("JB 700", "jb700"),
            new VehicleEntry("JB 700W", "jb7002"),
            new VehicleEntry("Mamba", "mamba"),
            new VehicleEntry("Manana", "manana"),
            new VehicleEntry("Michelli GT", "michelli"),
            new VehicleEntry("Monroe", "monroe"),
            new VehicleEntry("Nebula Turbo", "nebula"),
            new VehicleEntry("Peyote", "peyote"),
            new VehicleEntry("Peyote Custom", "peyote3"),
            new VehicleEntry("Pigalle", "pigalle"),
            new VehicleEntry("Rapid GT Classic", "rapidgt3"),
            new VehicleEntry("Retinue", "retinue"),
            new VehicleEntry("Retinue Mk II", "retinue2"),
            new VehicleEntry("Savestra", "savestra"),
            new VehicleEntry("Stinger", "stinger"),
            new VehicleEntry("Stinger GT", "stingergt"),
            new VehicleEntry("Stromberg", "stromberg"),
            new VehicleEntry("Swinger", "swinger"),
            new VehicleEntry("Toreador", "toreador"),
            new VehicleEntry("Torero", "torero"),
            new VehicleEntry("Tornado", "tornado"),
            new VehicleEntry("Tornado", "tornado2"),
            new VehicleEntry("Tornado", "tornado3"),
            new VehicleEntry("Tornado", "tornado4"),
            new VehicleEntry("Tornado Custom", "tornado5"),
            new VehicleEntry("Tornado Rat Rod", "tornado6"),
            new VehicleEntry("Turismo Classic", "turismo2"),
            new VehicleEntry("Viseris", "viseris"),
            new VehicleEntry("190z", "z190"),
            new VehicleEntry("Zion Classic", "zion3"),
            new VehicleEntry("Z-Type", "ztype"),
        }),
        new VehicleCategory("Sports", new VehicleEntry[]
        {
            new VehicleEntry("Alpha", "alpha"),
            new VehicleEntry("Banshee", "banshee"),
            new VehicleEntry("Bestia GTS", "bestiagts"),
            new VehicleEntry("Blista Compact", "blista2"),
            new VehicleEntry("Go Go Monkey Blista", "blista3"),
            new VehicleEntry("Buffalo", "buffalo"),
            new VehicleEntry("Buffalo S", "buffalo2"),
            new VehicleEntry("Sprunk Buffalo", "buffalo3"),
            new VehicleEntry("Calico GTF", "calico"),
            new VehicleEntry("Carbonizzare", "carbonizzare"),
            new VehicleEntry("Comet", "comet2"),
            new VehicleEntry("Comet Retro Custom", "comet3"),
            new VehicleEntry("Comet Safari", "comet4"),
            new VehicleEntry("Comet SR", "comet5"),
            new VehicleEntry("Comet S2", "comet6"),
            new VehicleEntry("Comet S2 Cabrio", "comet7"),
            new VehicleEntry("Coquette", "coquette"),
            new VehicleEntry("Coquette D10", "coquette4"),
            new VehicleEntry("Corsita", "corsita"),
            new VehicleEntry("La Coureuse", "coureur"),
            new VehicleEntry("Cypher", "cypher"),
            new VehicleEntry("8F Drafter", "drafter"),
            new VehicleEntry("Euros", "drifteuros"),
            new VehicleEntry("Futo GTX", "driftfuto"),
            new VehicleEntry("Jester RR", "driftjester"),
            new VehicleEntry("Remus", "driftremus"),
            new VehicleEntry("Drift Tampa", "drifttampa"),
            new VehicleEntry("ZR350", "driftzr350"),
            new VehicleEntry("Elegy Retro Custom", "elegy"),
            new VehicleEntry("Elegy RH8", "elegy2"),
            new VehicleEntry("Euros", "euros"),
            new VehicleEntry("Hotring Everon", "everon2"),
            new VehicleEntry("Feltzer", "feltzer2"),
            new VehicleEntry("Flash GT", "flashgt"),
            new VehicleEntry("Furore GT", "furoregt"),
            new VehicleEntry("Fusilade", "fusilade"),
            new VehicleEntry("Futo", "futo"),
            new VehicleEntry("Futo GTX", "futo2"),
            new VehicleEntry("Hotring Hellfire", "gauntlet6"),
            new VehicleEntry("GB200", "gb200"),
            new VehicleEntry("Growler", "growler"),
            new VehicleEntry("Hotring Sabre", "hotring"),
            new VehicleEntry("Imorgon", "imorgon"),
            new VehicleEntry("Issi Sport", "issi7"),
            new VehicleEntry("Itali GTO", "italigto"),
            new VehicleEntry("Itali RSX", "italirsx"),
            new VehicleEntry("Jester", "jester"),
            new VehicleEntry("Jester (Racecar)", "jester2"),
            new VehicleEntry("Jester Classic", "jester3"),
            new VehicleEntry("Jester RR", "jester4"),
            new VehicleEntry("Jugular", "jugular"),
            new VehicleEntry("Khamelion", "khamelion"),
            new VehicleEntry("Komoda", "komoda"),
            new VehicleEntry("Kuruma", "kuruma"),
            new VehicleEntry("Kuruma (Armored)", "kuruma2"),
            new VehicleEntry("Locust", "locust"),
            new VehicleEntry("Lynx", "lynx"),
            new VehicleEntry("Massacro", "massacro"),
            new VehicleEntry("Massacro (Racecar)", "massacro2"),
            new VehicleEntry("Neo", "neo"),
            new VehicleEntry("Neon", "neon"),
            new VehicleEntry("9F", "ninef"),
            new VehicleEntry("9F Cabrio", "ninef2"),
            new VehicleEntry("Omnis", "omnis"),
            new VehicleEntry("Omnis e-GT", "omnisegt"),
            new VehicleEntry("Panthere", "panthere"),
            new VehicleEntry("Paragon R", "paragon"),
            new VehicleEntry("Paragon R (Armored)", "paragon2"),
            new VehicleEntry("Pariah", "pariah"),
            new VehicleEntry("Penumbra", "penumbra"),
            new VehicleEntry("Penumbra FF", "penumbra2"),
            new VehicleEntry("300R", "r300"),
            new VehicleEntry("Raiden", "raiden"),
            new VehicleEntry("Rapid GT", "rapidgt"),
            new VehicleEntry("Rapid GT", "rapidgt2"),
            new VehicleEntry("Rapid GT X", "rapidgt4"),
            new VehicleEntry("Raptor", "raptor"),
            new VehicleEntry("Remus", "remus"),
            new VehicleEntry("Revolter", "revolter"),
            new VehicleEntry("RT3000", "rt3000"),
            new VehicleEntry("Ruston", "ruston"),
            new VehicleEntry("Schafter V12", "schafter3"),
            new VehicleEntry("Schafter LWB", "schafter4"),
            new VehicleEntry("Schlagen GT", "schlagen"),
            new VehicleEntry("Schwartzer", "schwarzer"),
            new VehicleEntry("Sentinel", "sentinel3"),
            new VehicleEntry("Sentinel Classic Widebody", "sentinel4"),
            new VehicleEntry("Sentinel GTS", "sentinel5"),
            new VehicleEntry("Seven-70", "seven70"),
            new VehicleEntry("SM722", "sm722"),
            new VehicleEntry("Specter", "specter"),
            new VehicleEntry("Specter Custom", "specter2"),
            new VehicleEntry("Itali GTO Stinger TT", "stingertt"),
            new VehicleEntry("Streiter", "streiter"),
            new VehicleEntry("Sugoi", "sugoi"),
            new VehicleEntry("Sultan", "sultan"),
            new VehicleEntry("Sultan Classic", "sultan2"),
            new VehicleEntry("Sultan RS Classic", "sultan3"),
            new VehicleEntry("Surano", "surano"),
            new VehicleEntry("Drift Tampa", "tampa2"),
            new VehicleEntry("10F", "tenf"),
            new VehicleEntry("10F Widebody", "tenf2"),
            new VehicleEntry("Tropos Rallye", "tropos"),
            new VehicleEntry("Vectre", "vectre"),
            new VehicleEntry("Verlierer", "verlierer2"),
            new VehicleEntry("Veto Classic", "veto"),
            new VehicleEntry("Veto Modern", "veto2"),
            new VehicleEntry("V-STR", "vstr"),
            new VehicleEntry("ZR350", "zr350"),
            new VehicleEntry("Apocalypse ZR380", "zr380"),
            new VehicleEntry("Future Shock ZR380", "zr3802"),
            new VehicleEntry("Nightmare ZR380", "zr3803"),
        }),
        new VehicleCategory("Super", new VehicleEntry[]
        {
            new VehicleEntry("Adder", "adder"),
            new VehicleEntry("Autarch", "autarch"),
            new VehicleEntry("Banshee 900R", "banshee2"),
            new VehicleEntry("Bullet", "bullet"),
            new VehicleEntry("Champion", "champion"),
            new VehicleEntry("Cheetah", "cheetah"),
            new VehicleEntry("Cyclone", "cyclone"),
            new VehicleEntry("Deveste Eight", "deveste"),
            new VehicleEntry("Emerus", "emerus"),
            new VehicleEntry("Entity XXR", "entity2"),
            new VehicleEntry("Entity MT", "entity3"),
            new VehicleEntry("Entity XF", "entityxf"),
            new VehicleEntry("FMJ", "fmj"),
            new VehicleEntry("Furia", "furia"),
            new VehicleEntry("GP1", "gp1"),
            new VehicleEntry("Ignus", "ignus"),
            new VehicleEntry("Infernus", "infernus"),
            new VehicleEntry("Itali GTB", "italigtb"),
            new VehicleEntry("Itali GTB Custom", "italigtb2"),
            new VehicleEntry("Krieger", "krieger"),
            new VehicleEntry("RE-7B", "le7b"),
            new VehicleEntry("LM87", "lm87"),
            new VehicleEntry("Nero", "nero"),
            new VehicleEntry("Nero Custom", "nero2"),
            new VehicleEntry("Osiris", "osiris"),
            new VehicleEntry("Penetrator", "penetrator"),
            new VehicleEntry("811", "pfister811"),
            new VehicleEntry("X80 Proto", "prototipo"),
            new VehicleEntry("Reaper", "reaper"),
            new VehicleEntry("S80RR", "s80"),
            new VehicleEntry("SC1", "sc1"),
            new VehicleEntry("Scramjet", "scramjet"),
            new VehicleEntry("ETR1", "sheava"),
            new VehicleEntry("Sultan RS", "sultanrs"),
            new VehicleEntry("Suzume", "suzume"),
            new VehicleEntry("T20", "t20"),
            new VehicleEntry("Taipan", "taipan"),
            new VehicleEntry("Tempesta", "tempesta"),
            new VehicleEntry("Tezeract", "tezeract"),
            new VehicleEntry("Thrax", "thrax"),
            new VehicleEntry("Tigon", "tigon"),
            new VehicleEntry("Torero XO", "torero2"),
            new VehicleEntry("Turismo Omaggio", "turismo3"),
            new VehicleEntry("Turismo R", "turismor"),
            new VehicleEntry("Tyrant", "tyrant"),
            new VehicleEntry("Tyrus", "tyrus"),
            new VehicleEntry("Vacca", "vacca"),
            new VehicleEntry("Vagner", "vagner"),
            new VehicleEntry("Vigilante", "vigilante"),
            new VehicleEntry("Virtue", "virtue"),
            new VehicleEntry("Visione", "visione"),
            new VehicleEntry("Voltic", "voltic"),
            new VehicleEntry("Rocket Voltic", "voltic2"),
            new VehicleEntry("XA-21", "xa21"),
            new VehicleEntry("Zeno", "zeno"),
            new VehicleEntry("Zentorno", "zentorno"),
            new VehicleEntry("Zorrusso", "zorrusso"),
        }),
        new VehicleCategory("Motorcycles", new VehicleEntry[]
        {
            new VehicleEntry("Akuma", "akuma"),
            new VehicleEntry("Avarus", "avarus"),
            new VehicleEntry("Bagger", "bagger"),
            new VehicleEntry("Bati 801", "bati"),
            new VehicleEntry("Bati 801RR", "bati2"),
            new VehicleEntry("BF400", "bf400"),
            new VehicleEntry("Carbon RS", "carbonrs"),
            new VehicleEntry("Chimera", "chimera"),
            new VehicleEntry("Cliffhanger", "cliffhanger"),
            new VehicleEntry("Daemon", "daemon"),
            new VehicleEntry("Daemon Custom", "daemon2"),
            new VehicleEntry("Apocalypse Deathbike", "deathbike"),
            new VehicleEntry("Future Shock Deathbike", "deathbike2"),
            new VehicleEntry("Nightmare Deathbike", "deathbike3"),
            new VehicleEntry("Defiler", "defiler"),
            new VehicleEntry("Diabolus", "diablous"),
            new VehicleEntry("Diabolus Custom", "diablous2"),
            new VehicleEntry("Double-T", "double"),
            new VehicleEntry("Enduro", "enduro"),
            new VehicleEntry("Esskey", "esskey"),
            new VehicleEntry("Faggio Sport", "faggio"),
            new VehicleEntry("Faggio", "faggio2"),
            new VehicleEntry("Faggio Mod", "faggio3"),
            new VehicleEntry("FCR 1000", "fcr"),
            new VehicleEntry("FCR 1000 Custom", "fcr2"),
            new VehicleEntry("Gargoyle", "gargoyle"),
            new VehicleEntry("Hakuchou", "hakuchou"),
            new VehicleEntry("Hakuchou Drag", "hakuchou2"),
            new VehicleEntry("Hexer", "hexer"),
            new VehicleEntry("Innovation", "innovation"),
            new VehicleEntry("Lectro", "lectro"),
            new VehicleEntry("Manchez", "manchez"),
            new VehicleEntry("Manchez Scout", "manchez2"),
            new VehicleEntry("Manchez Scout C", "manchez3"),
            new VehicleEntry("Nemesis", "nemesis"),
            new VehicleEntry("Nightblade", "nightblade"),
            new VehicleEntry("Oppressor", "oppressor"),
            new VehicleEntry("Oppressor Mk II", "oppressor2"),
            new VehicleEntry("PCJ 600", "pcj"),
            new VehicleEntry("Powersurge", "powersurge"),
            new VehicleEntry("Rat Bike", "ratbike"),
            new VehicleEntry("Reever", "reever"),
            new VehicleEntry("Rampant Rocket", "rrocket"),
            new VehicleEntry("Ruffian", "ruffian"),
            new VehicleEntry("Sanchez (livery)", "sanchez"),
            new VehicleEntry("Sanchez", "sanchez2"),
            new VehicleEntry("Sanctus", "sanctus"),
            new VehicleEntry("Shinobi", "shinobi"),
            new VehicleEntry("Shotaro", "shotaro"),
            new VehicleEntry("Sovereign", "sovereign"),
            new VehicleEntry("Stryder", "stryder"),
            new VehicleEntry("Thrust", "thrust"),
            new VehicleEntry("Vader", "vader"),
            new VehicleEntry("Vindicator", "vindicator"),
            new VehicleEntry("Vortex", "vortex"),
            new VehicleEntry("Wolfsbane", "wolfsbane"),
            new VehicleEntry("Zombie Bobber", "zombiea"),
            new VehicleEntry("Zombie Chopper", "zombieb"),
        }),
        new VehicleCategory("Off-Road", new VehicleEntry[]
        {
            new VehicleEntry("Injection", "bfinjection"),
            new VehicleEntry("Bifta", "bifta"),
            new VehicleEntry("Blazer", "blazer"),
            new VehicleEntry("Blazer Lifeguard", "blazer2"),
            new VehicleEntry("Hot Rod Blazer", "blazer3"),
            new VehicleEntry("Street Blazer", "blazer4"),
            new VehicleEntry("Blazer Aqua", "blazer5"),
            new VehicleEntry("Bodhi", "bodhi2"),
            new VehicleEntry("Boor", "boor"),
            new VehicleEntry("Brawler", "brawler"),
            new VehicleEntry("Apocalypse Bruiser", "bruiser"),
            new VehicleEntry("Future Shock Bruiser", "bruiser2"),
            new VehicleEntry("Nightmare Bruiser", "bruiser3"),
            new VehicleEntry("Apocalypse Brutus", "brutus"),
            new VehicleEntry("Future Shock Brutus", "brutus2"),
            new VehicleEntry("Nightmare Brutus", "brutus3"),
            new VehicleEntry("Caracara", "caracara"),
            new VehicleEntry("Caracara 4x4", "caracara2"),
            new VehicleEntry("Duneloader", "dloader"),
            new VehicleEntry("Draugur", "draugur"),
            new VehicleEntry("Drift Walkton L35", "driftl352"),
            new VehicleEntry("Dubsta 6x6", "dubsta3"),
            new VehicleEntry("Dune Buggy", "dune"),
            new VehicleEntry("Space Docker", "dune2"),
            new VehicleEntry("Dune FAV", "dune3"),
            new VehicleEntry("Ramp Buggy", "dune4"),
            new VehicleEntry("Ramp Buggy", "dune5"),
            new VehicleEntry("Freecrawler", "freecrawler"),
            new VehicleEntry("Hellion", "hellion"),
            new VehicleEntry("Insurgent Pick-Up", "insurgent"),
            new VehicleEntry("Insurgent", "insurgent2"),
            new VehicleEntry("Insurgent Pick-Up Custom", "insurgent3"),
            new VehicleEntry("Kalahari", "kalahari"),
            new VehicleEntry("Kamacho", "kamacho"),
            new VehicleEntry("Walton L35", "l35"),
            new VehicleEntry("Walton L35 Stock", "l352"),
            new VehicleEntry("Marshall", "marshall"),
            new VehicleEntry("Menacer", "menacer"),
            new VehicleEntry("Mesa", "mesa3"),
            new VehicleEntry("Monster", "monster"),
            new VehicleEntry("Apocalypse Sasquatch", "monster3"),
            new VehicleEntry("Future Shock Sasquatch", "monster4"),
            new VehicleEntry("Nightmare Sasquatch", "monster5"),
            new VehicleEntry("MonstroCiti", "monstrociti"),
            new VehicleEntry("Nightshark", "nightshark"),
            new VehicleEntry("Outlaw", "outlaw"),
            new VehicleEntry("Patriot Mil-Spec", "patriot3"),
            new VehicleEntry("Rancher XL", "rancherxl"),
            new VehicleEntry("Rancher XL", "rancherxl2"),
            new VehicleEntry("Ratel", "ratel"),
            new VehicleEntry("RC Bandito", "rcbandito"),
            new VehicleEntry("Rusty Rebel", "rebel"),
            new VehicleEntry("Rebel", "rebel2"),
            new VehicleEntry("Riata", "riata"),
            new VehicleEntry("Sandking XL", "sandking"),
            new VehicleEntry("Sandking SWB", "sandking2"),
            new VehicleEntry("Technical", "technical"),
            new VehicleEntry("Technical Aqua", "technical2"),
            new VehicleEntry("Technical Custom", "technical3"),
            new VehicleEntry("Terminus", "terminus"),
            new VehicleEntry("Trophy Truck", "trophytruck"),
            new VehicleEntry("Desert Raid", "trophytruck2"),
            new VehicleEntry("Vagrant", "vagrant"),
            new VehicleEntry("Verus", "verus"),
            new VehicleEntry("Winky", "winky"),
            new VehicleEntry("Yosemite Rancher", "yosemite3"),
            new VehicleEntry("Zhaba", "zhaba"),
        }),
        new VehicleCategory("Industrial", new VehicleEntry[]
        {
            new VehicleEntry("Dozer", "bulldozer"),
            new VehicleEntry("Cutter", "cutter"),
            new VehicleEntry("Dump", "dump"),
            new VehicleEntry("Flatbed", "flatbed"),
            new VehicleEntry("Custom Flatbed", "flatbed2"),
            new VehicleEntry("Guardian", "guardian"),
            new VehicleEntry("Dock Handler", "handler"),
            new VehicleEntry("Mixer", "mixer"),
            new VehicleEntry("Mixer", "mixer2"),
            new VehicleEntry("Rubble", "rubble"),
            new VehicleEntry("Tipper", "tiptruck"),
            new VehicleEntry("Tipper", "tiptruck2"),
        }),
        new VehicleCategory("Utility", new VehicleEntry[]
        {
            new VehicleEntry("Airtug", "airtug"),
            new VehicleEntry("Army Trailer", "armytanker"),
            new VehicleEntry("Army Trailer", "armytrailer"),
            new VehicleEntry("Army Trailer", "armytrailer2"),
            new VehicleEntry("Baletrailer", "baletrailer"),
            new VehicleEntry("Boat Trailer", "boattrailer"),
            new VehicleEntry("Boat Trailer", "boattrailer2"),
            new VehicleEntry("Boat Trailer", "boattrailer3"),
            new VehicleEntry("Caddy", "caddy"),
            new VehicleEntry("Caddy", "caddy2"),
            new VehicleEntry("Caddy", "caddy3"),
            new VehicleEntry("null", "docktrailer"),
            new VehicleEntry("Docktug", "docktug"),
            new VehicleEntry("Forklift", "forklift"),
            new VehicleEntry("null", "freighttrailer"),
            new VehicleEntry("Graintrailer", "graintrailer"),
            new VehicleEntry("Lawn Mower", "mower"),
            new VehicleEntry("null", "proptrailer"),
            new VehicleEntry("Trailer", "raketrailer"),
            new VehicleEntry("Ripley", "ripley"),
            new VehicleEntry("Sadler", "sadler"),
            new VehicleEntry("Sadler", "sadler2"),
            new VehicleEntry("Scrap Truck", "scrap"),
            new VehicleEntry("Slamtruck", "slamtruck"),
            new VehicleEntry("Trailer", "tanker"),
            new VehicleEntry("null", "tanker2"),
            new VehicleEntry("Tow Truck", "towtruck"),
            new VehicleEntry("Tow Truck", "towtruck2"),
            new VehicleEntry("Tow Truck", "towtruck3"),
            new VehicleEntry("Tow Truck", "towtruck4"),
            new VehicleEntry("Trailer", "tr2"),
            new VehicleEntry("Trailer", "tr3"),
            new VehicleEntry("Trailer", "tr4"),
            new VehicleEntry("Tractor", "tractor"),
            new VehicleEntry("Fieldmaster", "tractor2"),
            new VehicleEntry("Fieldmaster", "tractor3"),
            new VehicleEntry("Mobile Operations Center", "trailerlarge"),
            new VehicleEntry("Trailer", "trailerlogs"),
            new VehicleEntry("Trailer", "trailers"),
            new VehicleEntry("Trailer", "trailers2"),
            new VehicleEntry("Trailer", "trailers3"),
            new VehicleEntry("Trailer", "trailers4"),
            new VehicleEntry("Trailer", "trailers5"),
            new VehicleEntry("Trailer", "trailersmall"),
            new VehicleEntry("Trailer", "trflat"),
            new VehicleEntry("Trailer", "tvtrailer"),
            new VehicleEntry("Trailer", "tvtrailer2"),
            new VehicleEntry("Utility Truck", "utillitruck"),
            new VehicleEntry("Utility Truck", "utillitruck2"),
            new VehicleEntry("Utility Truck", "utillitruck3"),
        }),
        new VehicleCategory("Vans", new VehicleEntry[]
        {
            new VehicleEntry("Bison", "bison"),
            new VehicleEntry("Bison", "bison2"),
            new VehicleEntry("Bison", "bison3"),
            new VehicleEntry("Bobcat XL", "bobcatxl"),
            new VehicleEntry("Boxville", "boxville"),
            new VehicleEntry("Boxville", "boxville2"),
            new VehicleEntry("Boxville", "boxville3"),
            new VehicleEntry("Boxville", "boxville4"),
            new VehicleEntry("Armored Boxville", "boxville5"),
            new VehicleEntry("Boxville (LSDS)", "boxville6"),
            new VehicleEntry("Burrito", "burrito"),
            new VehicleEntry("Bugstars Burrito", "burrito2"),
            new VehicleEntry("Burrito", "burrito3"),
            new VehicleEntry("Burrito", "burrito4"),
            new VehicleEntry("Burrito", "burrito5"),
            new VehicleEntry("Camper", "camper"),
            new VehicleEntry("Gang Burrito", "gburrito"),
            new VehicleEntry("Gang Burrito", "gburrito2"),
            new VehicleEntry("Journey", "journey"),
            new VehicleEntry("Journey II", "journey2"),
            new VehicleEntry("Minivan", "minivan"),
            new VehicleEntry("Minivan Custom", "minivan2"),
            new VehicleEntry("Paradise", "paradise"),
            new VehicleEntry("Pony", "pony"),
            new VehicleEntry("Pony", "pony2"),
            new VehicleEntry("Rumpo", "rumpo"),
            new VehicleEntry("Rumpo", "rumpo2"),
            new VehicleEntry("Rumpo Custom", "rumpo3"),
            new VehicleEntry("Speedo", "speedo"),
            new VehicleEntry("Clown Van", "speedo2"),
            new VehicleEntry("Speedo Custom", "speedo4"),
            new VehicleEntry("Speedo Custom", "speedo5"),
            new VehicleEntry("Surfer", "surfer"),
            new VehicleEntry("Surfer", "surfer2"),
            new VehicleEntry("Surfer Custom", "surfer3"),
            new VehicleEntry("Taco Van", "taco"),
            new VehicleEntry("Youga", "youga"),
            new VehicleEntry("Youga Classic", "youga2"),
            new VehicleEntry("Youga Classic 4x4", "youga3"),
            new VehicleEntry("Youga Custom", "youga4"),
        }),
        new VehicleCategory("Cycles", new VehicleEntry[]
        {
            new VehicleEntry("BMX", "bmx"),
            new VehicleEntry("Cruiser", "cruiser"),
            new VehicleEntry("Fixter", "fixter"),
            new VehicleEntry("Inductor", "inductor"),
            new VehicleEntry("Junk Energy Inductor", "inductor2"),
            new VehicleEntry("Scorcher", "scorcher"),
            new VehicleEntry("Whippet Race Bike", "tribike"),
            new VehicleEntry("Endurex Race Bike", "tribike2"),
            new VehicleEntry("Tri-Cycles Race Bike", "tribike3"),
        }),
        new VehicleCategory("Boats", new VehicleEntry[]
        {
            new VehicleEntry("Avisa", "avisa"),
            new VehicleEntry("Dinghy", "dinghy"),
            new VehicleEntry("Dinghy", "dinghy2"),
            new VehicleEntry("Dinghy", "dinghy3"),
            new VehicleEntry("Dinghy", "dinghy4"),
            new VehicleEntry("Weaponized Dinghy", "dinghy5"),
            new VehicleEntry("Jetmax", "jetmax"),
            new VehicleEntry("Kosatka", "kosatka"),
            new VehicleEntry("Longfin", "longfin"),
            new VehicleEntry("Marquis", "marquis"),
            new VehicleEntry("Kurtz 31 Patrol Boat", "patrolboat"),
            new VehicleEntry("Police Predator", "predator"),
            new VehicleEntry("Seashark", "seashark"),
            new VehicleEntry("Seashark", "seashark2"),
            new VehicleEntry("Seashark", "seashark3"),
            new VehicleEntry("Speeder", "speeder"),
            new VehicleEntry("Speeder", "speeder2"),
            new VehicleEntry("Squalo", "squalo"),
            new VehicleEntry("Submersible", "submersible"),
            new VehicleEntry("Kraken", "submersible2"),
            new VehicleEntry("Suntrap", "suntrap"),
            new VehicleEntry("Toro", "toro"),
            new VehicleEntry("Toro", "toro2"),
            new VehicleEntry("Tropic", "tropic"),
            new VehicleEntry("Tropic", "tropic2"),
            new VehicleEntry("Tug", "tug"),
        }),
        new VehicleCategory("Helicopters", new VehicleEntry[]
        {
            new VehicleEntry("Akula", "akula"),
            new VehicleEntry("Annihilator", "annihilator"),
            new VehicleEntry("Annihilator Stealth", "annihilator2"),
            new VehicleEntry("Buzzard Attack Chopper", "buzzard"),
            new VehicleEntry("Buzzard", "buzzard2"),
            new VehicleEntry("Cargobob", "cargobob"),
            new VehicleEntry("Cargobob", "cargobob2"),
            new VehicleEntry("Cargobob", "cargobob3"),
            new VehicleEntry("Cargobob", "cargobob4"),
            new VehicleEntry("Conada", "conada"),
            new VehicleEntry("Weaponized Conada", "conada2"),
            new VehicleEntry("Frogger", "frogger"),
            new VehicleEntry("Frogger", "frogger2"),
            new VehicleEntry("Havok", "havok"),
            new VehicleEntry("FH-1 Hunter", "hunter"),
            new VehicleEntry("Maverick", "maverick"),
            new VehicleEntry("Higgins Helitours Maverick", "maverick2"),
            new VehicleEntry("Police Maverick", "polmav"),
            new VehicleEntry("Savage", "savage"),
            new VehicleEntry("Sea Sparrow", "seasparrow"),
            new VehicleEntry("Sparrow", "seasparrow2"),
            new VehicleEntry("Sparrow", "seasparrow3"),
            new VehicleEntry("Skylift", "skylift"),
            new VehicleEntry("SuperVolito", "supervolito"),
            new VehicleEntry("SuperVolito Carbon", "supervolito2"),
            new VehicleEntry("Swift", "swift"),
            new VehicleEntry("Swift Deluxe", "swift2"),
            new VehicleEntry("Valkyrie", "valkyrie"),
            new VehicleEntry("Valkyrie MOD.0", "valkyrie2"),
            new VehicleEntry("Volatus", "volatus"),
        }),
        new VehicleCategory("Planes", new VehicleEntry[]
        {
            new VehicleEntry("RO-86 Alkonost", "alkonost"),
            new VehicleEntry("Alpha-Z1", "alphaz1"),
            new VehicleEntry("Avenger", "avenger"),
            new VehicleEntry("Avenger", "avenger2"),
            new VehicleEntry("Avenger", "avenger3"),
            new VehicleEntry("Avenger", "avenger4"),
            new VehicleEntry("Besra", "besra"),
            new VehicleEntry("Atomic Blimp", "blimp"),
            new VehicleEntry("Xero Blimp", "blimp2"),
            new VehicleEntry("Blimp", "blimp3"),
            new VehicleEntry("RM-10 Bombushka", "bombushka"),
            new VehicleEntry("Cargo Plane", "cargoplane"),
            new VehicleEntry("Cargo Plane", "cargoplane2"),
            new VehicleEntry("Cuban 800", "cuban800"),
            new VehicleEntry("Dodo", "dodo"),
            new VehicleEntry("Duster", "duster"),
            new VehicleEntry("Howard NX-25", "howard"),
            new VehicleEntry("Hydra", "hydra"),
            new VehicleEntry("Jet", "jet"),
            new VehicleEntry("P-996 LAZER", "lazer"),
            new VehicleEntry("Luxor", "luxor"),
            new VehicleEntry("Luxor Deluxe", "luxor2"),
            new VehicleEntry("Mammatus", "mammatus"),
            new VehicleEntry("Ultralight", "microlight"),
            new VehicleEntry("Miljet", "miljet"),
            new VehicleEntry("Mogul", "mogul"),
            new VehicleEntry("V-65 Molotok", "molotok"),
            new VehicleEntry("Nimbus", "nimbus"),
            new VehicleEntry("P-45 Nokota", "nokota"),
            new VehicleEntry("Pyro", "pyro"),
            new VehicleEntry("F-160 Raiju", "raiju"),
            new VehicleEntry("Rogue", "rogue"),
            new VehicleEntry("Seabreeze", "seabreeze"),
            new VehicleEntry("Shamal", "shamal"),
            new VehicleEntry("LF-22 Starling", "starling"),
            new VehicleEntry("Streamer216", "streamer216"),
            new VehicleEntry("B-11 Strikeforce", "strikeforce"),
            new VehicleEntry("Mallard", "stunt"),
            new VehicleEntry("Titan", "titan"),
            new VehicleEntry("Tula", "tula"),
            new VehicleEntry("Velum", "velum"),
            new VehicleEntry("Velum 5-Seater", "velum2"),
            new VehicleEntry("Vestra", "vestra"),
            new VehicleEntry("Volatol", "volatol"),
        }),
        new VehicleCategory("Service", new VehicleEntry[]
        {
            new VehicleEntry("Airport Bus", "airbus"),
            new VehicleEntry("Brickade", "brickade"),
            new VehicleEntry("Brickade 6x6", "brickade2"),
            new VehicleEntry("Bus", "bus"),
            new VehicleEntry("Dashound", "coach"),
            new VehicleEntry("Festival Bus", "pbus2"),
            new VehicleEntry("Dune", "rallytruck"),
            new VehicleEntry("Rental Shuttle Bus", "rentalbus"),
            new VehicleEntry("Taxi", "taxi"),
            new VehicleEntry("Tour Bus", "tourbus"),
            new VehicleEntry("Trashmaster", "trash"),
            new VehicleEntry("Trashmaster", "trash2"),
            new VehicleEntry("Wastelander", "wastelander"),
        }),
        new VehicleCategory("Emergency", new VehicleEntry[]
        {
            new VehicleEntry("Ambulance", "ambulance"),
            new VehicleEntry("FIB", "fbi"),
            new VehicleEntry("FIB", "fbi2"),
            new VehicleEntry("Fire Truck", "firetruk"),
            new VehicleEntry("Lifeguard", "lguard"),
            new VehicleEntry("Police Prison Bus", "pbus"),
            new VehicleEntry("Gauntlet Interceptor", "polgauntlet"),
            new VehicleEntry("Police Cruiser", "police"),
            new VehicleEntry("Police Cruiser", "police2"),
            new VehicleEntry("Police Cruiser", "police3"),
            new VehicleEntry("Unmarked Cruiser", "police4"),
            new VehicleEntry("Stanier LE Cruiser", "police5"),
            new VehicleEntry("Police Bike", "policeb"),
            new VehicleEntry("Police Bike", "policeb2"),
            new VehicleEntry("Police Rancher", "policeold1"),
            new VehicleEntry("Police Roadcruiser", "policeold2"),
            new VehicleEntry("Police Transporter", "policet"),
            new VehicleEntry("Park Ranger", "pranger"),
            new VehicleEntry("Police Riot", "riot"),
            new VehicleEntry("RCV", "riot2"),
            new VehicleEntry("Sheriff Cruiser", "sheriff"),
            new VehicleEntry("Sheriff SUV", "sheriff2"),
        }),
        new VehicleCategory("Military", new VehicleEntry[]
        {
            new VehicleEntry("APC", "apc"),
            new VehicleEntry("Barracks", "barracks"),
            new VehicleEntry("Barracks Semi", "barracks2"),
            new VehicleEntry("Barracks", "barracks3"),
            new VehicleEntry("Barrage", "barrage"),
            new VehicleEntry("Chernobog", "chernobog"),
            new VehicleEntry("Crusader", "crusader"),
            new VehicleEntry("Half-track", "halftrack"),
            new VehicleEntry("TM-02 Khanjali", "khanjali"),
            new VehicleEntry("Invade and Persuade Tank", "minitank"),
            new VehicleEntry("Rhino Tank", "rhino"),
            new VehicleEntry("Apocalypse Scarab", "scarab"),
            new VehicleEntry("Future Shock Scarab", "scarab2"),
            new VehicleEntry("Nightmare Scarab", "scarab3"),
            new VehicleEntry("Thruster", "thruster"),
            new VehicleEntry("Anti-Aircraft Trailer", "trailersmall2"),
            new VehicleEntry("Vetir", "vetir"),
        }),
        new VehicleCategory("Commercial", new VehicleEntry[]
        {
            new VehicleEntry("Benson", "benson"),
            new VehicleEntry("Benson (Cluckin' Bell)", "benson2"),
            new VehicleEntry("Biff", "biff"),
            new VehicleEntry("Apocalypse Cerberus", "cerberus"),
            new VehicleEntry("Future Shock Cerberus", "cerberus2"),
            new VehicleEntry("Nightmare Cerberus", "cerberus3"),
            new VehicleEntry("Hauler", "hauler"),
            new VehicleEntry("Hauler Custom", "hauler2"),
            new VehicleEntry("Mule", "mule"),
            new VehicleEntry("Mule", "mule2"),
            new VehicleEntry("Mule", "mule3"),
            new VehicleEntry("Mule Custom", "mule4"),
            new VehicleEntry("Mule", "mule5"),
            new VehicleEntry("Packer", "packer"),
            new VehicleEntry("Phantom", "phantom"),
            new VehicleEntry("Phantom Wedge", "phantom2"),
            new VehicleEntry("Phantom Custom", "phantom3"),
            new VehicleEntry("Phantom", "phantom4"),
            new VehicleEntry("Pounder", "pounder"),
            new VehicleEntry("Pounder Custom", "pounder2"),
            new VehicleEntry("Stockade", "stockade"),
            new VehicleEntry("Stockade", "stockade3"),
            new VehicleEntry("Bobcat Security Stockade", "stockade4"),
            new VehicleEntry("Terrorbyte", "terbyte"),
        }),
        new VehicleCategory("Trains", new VehicleEntry[]
        {
            new VehicleEntry("Cable Car", "cablecar"),
            new VehicleEntry("Freight Train", "freight"),
            new VehicleEntry("Freight Train", "freight2"),
            new VehicleEntry("Freight Train", "freightcar"),
            new VehicleEntry("Freight Train", "freightcar2"),
            new VehicleEntry("Freight Train", "freightcont1"),
            new VehicleEntry("Freight Train", "freightcont2"),
            new VehicleEntry("Freight Train", "freightgrain"),
            new VehicleEntry("Freight Train", "metrotrain"),
            new VehicleEntry("Freight Train", "tankercar"),
        }),
        new VehicleCategory("Open Wheels", new VehicleEntry[]
        {
            new VehicleEntry("PR4", "formula"),
            new VehicleEntry("R88", "formula2"),
            new VehicleEntry("BR8", "openwheel1"),
            new VehicleEntry("DR1", "openwheel2"),
        }),
    };
}
